#pragma once

#define UTILS_ASCII_CHAR_SIZE 5
#define UTILS_ASCII_CHARACTER_COUNT 96
#define UTILS_ASCII_CHARACTER_START_INDEX 32
#define UTILS_ASCII_TABLE_SIZE UTILS_ASCII_CHARACTER_COUNT*UTILS_ASCII_CHAR_SIZE

#define UTILS_ASCII_TOP_PIXEL 0x04

const unsigned char utils_ascii_96_char_map[UTILS_ASCII_TABLE_SIZE];