#pragma once

#define VGA_13_ASCII_CHAR_SIZE 5
#define VGA_13_ASCII_CHAR_LENGHT 8
#define VGA_13_ASCII_CHAR_WIDTH 5
#define VGA_13_ASCII_CHARACTER_COUNT 96
#define VGA_13_ASCII_CHARACTER_START_INDEX 32
#define VGA_13_ASCII_TABLE_SIZE VGA_13_ASCII_CHARACTER_COUNT*VGA_13_ASCII_CHAR_SIZE

#define VGA_13_ASCII_TOP_PIXEL 0x01

const unsigned char VGA_13_ASCII_96_char_map[VGA_13_ASCII_TABLE_SIZE];